### ISSUE TITLE
how to resize image on markdown?

### ISSUE THREAD

**Issue by lookdeceline** [niklasmtj/gatsby-starter-julia#13]
the general syntax 
`![](./pic/pic1_50.png =100x20)`
doesn't seem to work. 
neither does 
`<img src="drawing.jpg" alt="drawing" width="200"/>`

**Comment by niklasmtj** [comment]
Hi,
the starter uses `gatsby-remark-images` to handle images from markdown files. 
It is possible to set a max-width in `gatsby-config` like this:
```
// In your gatsby-config.js
plugins: [
  `gatsby-plugin-sharp`,
  {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        {
          resolve: `gatsby-remark-images`,
          options: {
            // It's important to specify the maxWidth (in pixels) of
            // the content container as this plugin uses this as the
            // base for generating different widths of each image.
            maxWidth: 590,
          },
        },
      ],
    },
  },
]
```

But if you want to change it for just one image please check this link and see if this might work for you: (https://stackoverflow.com/a/14747656)
