### ISSUE TITLE
Markdown images link broken on Netlify

### ISSUE THREAD

**Issue by ctplt** [niklasmtj/gatsby-starter-julia#39]
Hello @niklasmtj, thanks for the brilliant starter!

I have been trying to add images but keep getting broken links. I am adding the in the src/images/ folder and invoked via MD on the posts, as usual. I have tried different syntaxes but nothing seems to work (i.e., './images/IMAGENAME.png' '/images/IMAGENAME.png' './IMAGENAME.png' '/IMAGENAME.png', etc.). Do you know what may be happening?

**Comment by niklasmtj** [comment]
Hey @mnlngl,
did you try using the `static` folder in Gatsby? There is none yet implemented in this starter but you can check out the documentation. I also use it on my own blog and it works fine.
Documentation: https://www.gatsbyjs.com/docs/how-to/images-and-media/static-folder/

**Comment by ctplt** [comment]
@niklasmtj Thank you so much! 🙏
This solved the issue (for some reason I thought that the gatsby plugins would render the images from src/images).
